[[stack]]
name = "{{ stack_name }}_{{ server_name }}"

[stack.config]
server = "{{ server_name }}"
file_paths = [ "docker-compose.yaml" ]
run_directory = "/home/shahvirb/gitsource/{{ server_name }}/{{ stack_name }}{% if stack_name == "stack-komodo-stack-gen" %}/docker{% endif %}"
{%- if has_git %}
git_provider = "github.com"
repo = "shahvirb/{{ stack_name }}"
clone_path = "/home/shahvirb/gitsource/{{ server_name }}/{{ stack_name }}"
{%- if stack_name in ["stack-komodo-stack-gen", "stack-smbcheck"] %}
auto_pull = false
{%- endif %}
{%- else %}
files_on_host = true
{%- endif %}
{% if op_unpack %}
[stack.config.pre_deploy]
path = ""
command = "/home/shahvirb/gitsource/utils/op-unpack.sh"
{% endif %}

